# Generated by Django 6.0 on 2026-01-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_company_alter_job_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
